#!/bin/bash
 java -jar sopc2dts.jar -v --input soc_system.sopcinfo\
  --output soc_system.dts\
  --type dts\
  --board board_info_DE0_NANO_SOC.xml\
  --board hps_common_board_info.xml\
  --board bridge_enable.xml\
  --board periphs_enable.xml\
  --bridge-removal all\
  --clocks \
  --reset

dtc -I dts -O dtb -o de0_board.dtb soc_system.dts
