#ifndef FPGA_IOC_CMDS
#define FPGA_IOC_CMDS

#include <sys/ioctl.h>

#define FPGA_IOC_MAGIC 0xb2

#define FPGA_IOC_READ_ID _IO(FPGA_IOC_MAGIC, 0xb3)
#define FPGA_IOC_READ_CTRL _IO(FPGA_IOC_MAGIC, 0xb4)
#define FPGA_IOC_READ_STATUS _IO(FPGA_IOC_MAGIC, 0xb5)
#define FPGA_IOC_READ_XOR_KEY _IO(FPGA_IOC_MAGIC, 0xb6)
#define FPGA_IOC_WRITE_CTRL _IO(FPGA_IOC_MAGIC, 0xb7)
#define FPGA_IOC_WRITE_ADDR _IO(FPGA_IOC_MAGIC, 0xb8)
#define FPGA_IOC_WRITE_LEN _IO(FPGA_IOC_MAGIC, 0xb9)
#define FPGA_IOC_WRITE_XOR_KEY _IO(FPGA_IOC_MAGIC, 0xc0)

#endif /* FPGA_IOC_CMDS */
